namespace BackRobotTDM.Scripts.SID.Models
{
    public class ResultModel
    {
        public string actaBis { get; set; }
        public string anioRegistro { get; set; }
        public string cadena { get; set; }
        public string curp { get; set; }
        public string curpAux1 { get; set; }
        public string curpAux2 { get; set; }
        public string curpMADRE { get; set; }
        public string curpPADRE { get; set; }
        public string estadoNac { get; set; }
        public string estadoNacNombre { get; set; }
        public string estadoNacReg { get; set; }
        public string estadoNacRegNombre { get; set; }
        public string estadoReg { get; set; }
        public string estadoRegNombre { get; set; }
        public string fechaNacimiento { get; set; }
        public string fechaRegistro { get; set; }
        public string foja { get; set; }
        public int folio { get; set; }
        public string libro { get; set; }
        public string localidad { get; set; }
        public string madre { get; set; }
        public string municipio { get; set; }
        public string municipioNac { get; set; }
        public string municipioNacNombre { get; set; }
        public string municipioNombre { get; set; }
        public string municipioReg { get; set; }
        public string municipioRegNombre { get; set; }
        public int nacMADRE { get; set; }
        public int nacPADRE { get; set; }
        public int nacionalidad { get; set; }
        public int nacionalidadAux1 { get; set; }
        public string nacionalidadAux1Txt { get; set; }
        public int nacionalidadAux2 { get; set; }
        public string nacionalidadAux2Txt { get; set; }
        public string nacionalidadTxt { get; set; }
        public string noActa { get; set; }
        public string nombre { get; set; }
        public string nombrePrimeraPersona { get; set; }
        public string nombreSegundaPersona { get; set; }
        public string notasMarginales { get; set; }
        public string numeroActa { get; set; }
        public string oficialia { get; set; }
        public string oficialiaNombre { get; set; }
        public string padre { get; set; }
        public int pais { get; set; }
        public string paisTxt { get; set; }
        public string primerApellido { get; set; }
        public string primerApellidoPrimeraPersona { get; set; }
        public string primerApellidoSegundaPersona { get; set; }
        public string segundoApellido { get; set; }
        public string segundoApellidoPrimeraPersona { get; set; }
        public string segundoApellidoSegundaPersona { get; set; }
        public string sello { get; set; }
        public string sexo { get; set; }
        public string ssa { get; set; }
        public string curpEl { get; set; }
        public string curpElla { get; set; }
        public string entidadCodigoNacElTxt { get; set; }
        public string entidadCodigoNacEllaTxt { get; set; }
        public string fechaNacimientoEl { get; set; }
        public string fechaNacimientoElla { get; set; }
        public string tipoNumActa { get; set; }
        public string tipoPersona { get; set; }
        public string tomo { get; set; }
        public string transcripcion { get; set; }
        public string vivoMuerto { get; set; }
        public string nacMadreTxt { get; set; }
        public string nacPadreTxt { get; set; }
    }
}
